export const API_URL = "https://ainaagent.infinitylearn.com/api/v1/session/reset-user-session";

// NOTE: In a production environment, sensitive tokens should be handled via a proxy server
// or environment variables, never hardcoded in the frontend bundle.
// Using the provided token for the requested implementation.
export const BEARER_TOKEN = "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3ODMxNjE3NTcsImlhdCI6MTc2NzYwOTc1NywidWFtX2lkIjo2MTYzMjA3LCJjcm5faWQiOiJDUk5QMzAwVDAwMDAxOUxNMVVZRiIsImJyYW5jaF9pZCI6IjAwODFhYzU2LTZiNTEtNDU4Ny05NjM1LTBiYmQyMDEzYTI3MCIsIkRCSWQiOiI2MTYzMjA3IiwiRmlyc3ROYW1lIjoibGlqbyIsIkxhc3ROYW1lIjoiYWJyYWhhbSIsInZlcnRpY2FsX2lkIjoxLCJ1aWQiOm51bGwsIlRlbmFudENvZGUiOiJJTCIsIlRlbmFudElkIjoiNTU2MDhlY2UtYzg2Ny00MzczLWEzY2YtM2U5NDkwMTM3ZmQ2IiwidW5pZmllZF9hY2NvdW50X2lkIjoiNDQzYTVlZjItNjhiNy00YzI4LWI5NTctYTQwNzk3MjZlNTJmIiwiaXNfb25lYXBwX3VzZXIiOnRydWUsIlJvbGVOYW1lIjoiU3R1ZGVudCIsIlJvbGVJZCI6IjEifQ.EzRoqPwfFDRcR6K445qq2skrNDLBqCJOnKhOaDwQQ94";